// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use std::fs;

fn generate_shader_header() {
    let bvh_src = fs::read_to_string("bvh.metal").expect("Failed to read bvh.metal");
    let hash_src =
        fs::read_to_string("spatial_hash.metal").expect("Failed to read spatial_hash.metal");
    let refine_src = fs::read_to_string("refine.metal").unwrap_or_default();
    let refine_exact_src = fs::read_to_string("refine_exact.metal").unwrap_or_default();

    let header_content = format!(
        r#"// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Auto-generated by build.rs from .metal source files. Do not edit directly.
#pragma once

static const char* BVH_METAL_SOURCE = R"RAW_SHADER(
{}
)RAW_SHADER";

static const char* SPATIAL_HASH_METAL_SOURCE = R"RAW_SHADER(
{}
)RAW_SHADER";

static const char* REFINE_METAL_SOURCE = R"RAW_SHADER(
{}
)RAW_SHADER";

static const char* REFINE_EXACT_METAL_SOURCE = R"RAW_SHADER(
{}
)RAW_SHADER";
"#,
        bvh_src, hash_src, refine_src, refine_exact_src
    );

    fs::write("metal_shaders.h", header_content).expect("Failed to write metal_shaders.h");
}

fn main() {
    println!("cargo:rerun-if-changed=spatial_index.hpp");
    println!("cargo:rerun-if-changed=spatial_index.mm");
    println!("cargo:rerun-if-changed=spatial_refiner.hpp");
    println!("cargo:rerun-if-changed=spatial_refiner.mm");
    println!("cargo:rerun-if-changed=sedona_metalspatial_c.h");
    println!("cargo:rerun-if-changed=sedona_metalspatial_c.mm");
    println!("cargo:rerun-if-changed=geom_types.hpp");
    println!("cargo:rerun-if-changed=box_intersection.metal");
    println!("cargo:rerun-if-changed=bvh.metal");
    println!("cargo:rerun-if-changed=refine.metal");
    println!("cargo:rerun-if-changed=refine_exact.metal");
    println!("cargo:rerun-if-changed=spatial_hash.metal");

    generate_shader_header();

    #[cfg(target_os = "macos")]
    {
        let mut build = cc::Build::new();
        build
            .cpp(true)
            .std("c++20")
            .flag("-fobjc-arc")
            .include(".")
            .file("spatial_index.mm")
            .file("spatial_refiner.mm")
            .file("sedona_metalspatial_c.mm");

        if std::env::var("CARGO_FEATURE_TEST_INTERNALS").is_ok() {
            build.define("ENABLE_TEST_INTERNALS", "1");
        }

        build.compile("sedona_metalspatial");

        println!("cargo:rustc-link-lib=framework=Metal");
        println!("cargo:rustc-link-lib=framework=Foundation");
    }
}
