// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Auto-generated by build.rs from .metal source files. Do not edit directly.
#pragma once

static const char* BVH_METAL_SOURCE = R"RAW_SHADER(
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#include <metal_stdlib>
#include <metal_raytracing>

using namespace metal;
using namespace metal::raytracing;

struct BoundingBox {
    float xmin;
    float ymin;
    float xmax;
    float ymax;
};

struct MatchPair {
    uint build_idx;
    uint probe_idx;
};

// =====================================================================
// Apple Silicon Metal 3 Hardware Ray Tracing Index Shader
// Uses primitive_acceleration_structure containing MTLAxisAlignedBoundingBox
// and inline intersection_query to traverse hardware BVH on RT cores.
// Exact geometric validation is performed to guarantee 100% precision.
// =====================================================================

inline bool is_valid_box(BoundingBox b) {
    return !(isnan(b.xmin) || isnan(b.ymin) || isnan(b.xmax) || isnan(b.ymax) ||
             isinf(b.xmin) || isinf(b.ymin) || isinf(b.xmax) || isinf(b.ymax) ||
             b.xmin > b.xmax || b.ymin > b.ymax);
}

kernel void rt_probe_points(
    primitive_acceleration_structure accel        [[buffer(0)]],
    device const BoundingBox*        build_boxes  [[buffer(1)]],
    device const BoundingBox*        probe_boxes  [[buffer(2)]],
    device MatchPair*                output_pairs [[buffer(3)]],
    device atomic_uint*              match_count  [[buffer(4)]],
    constant uint&                   num_probes   [[buffer(5)]],
    constant uint&                   max_results  [[buffer(6)]],
    constant uint&                   probe_offset [[buffer(7)]],
    uint                             tid          [[thread_position_in_grid]])
{
    if (tid >= num_probes) return;

    uint probe_idx = probe_offset + tid;
    BoundingBox probe = probe_boxes[probe_idx];
    if (!is_valid_box(probe)) return;

    float px = probe.xmin;
    float py = probe.ymin;

    // Cast vertical ray along Z-axis through (px, py)
    ray r;
    r.origin = float3(px, py, -1.0f);
    r.direction = float3(0.0f, 0.0f, 1.0f);
    r.min_distance = 0.0f;
    r.max_distance = 2.0f;

    // Inline ray query traversing the hardware BVH
    intersection_query<> q(r, accel);
    while (q.next()) {
        if (q.get_candidate_intersection_type() == intersection_type::bounding_box) {
            uint build_id = q.get_candidate_primitive_id();
            BoundingBox b = build_boxes[build_id];
            // Exact geometric inclusion check (inclusive boundaries matching SedonaDB)
            if (is_valid_box(b) && px >= b.xmin && px <= b.xmax && py >= b.ymin && py <= b.ymax) {
                uint slot = atomic_fetch_add_explicit(match_count, 1, memory_order_relaxed);
                if (slot < max_results) {
                    output_pairs[slot] = MatchPair{build_id, probe_idx};
                }
            }
        }
    }
}

)RAW_SHADER";

static const char* SPATIAL_HASH_METAL_SOURCE = R"RAW_SHADER(
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#include <metal_stdlib>
using namespace metal;

struct BoundingBox {
    float xmin;
    float ymin;
    float xmax;
    float ymax;
};

struct MatchPair {
    uint build_idx;
    uint probe_idx;
};

struct GridLevelParams {
    float cell_w;
    float cell_h;
    uint  grid_dim;
    uint  cell_offset;
};

struct HierarchicalGridParams {
    float min_x;
    float min_y;
    uint  num_levels;
    uint  num_build;
    uint  num_probe;
    uint  probe_offset;
    uint  max_results;
    GridLevelParams levels[4];
};

inline bool is_valid_box(BoundingBox b) {
    return !(isnan(b.xmin) || isnan(b.ymin) || isnan(b.xmax) || isnan(b.ymax) ||
             isinf(b.xmin) || isinf(b.ymin) || isinf(b.xmax) || isinf(b.ymax) ||
             b.xmin > b.xmax || b.ymin > b.ymax);
}

// Check if two 2D boxes intersect (inclusive boundaries)
inline bool boxes_intersect(BoundingBox a, BoundingBox b) {
    if (!is_valid_box(a) || !is_valid_box(b)) return false;
    return !(a.xmax < b.xmin || a.xmin > b.xmax || a.ymax < b.ymin || a.ymin > b.ymax);
}

inline void get_level_cell_range(BoundingBox b, constant HierarchicalGridParams& p, uint level,
                                 thread int& min_cx, thread int& max_cx,
                                 thread int& min_cy, thread int& max_cy)
{
    constant GridLevelParams& lp = p.levels[level];
    min_cx = clamp(int((b.xmin - p.min_x) / lp.cell_w), 0, int(lp.grid_dim - 1));
    max_cx = clamp(int((b.xmax - p.min_x) / lp.cell_w), 0, int(lp.grid_dim - 1));
    min_cy = clamp(int((b.ymin - p.min_y) / lp.cell_h), 0, int(lp.grid_dim - 1));
    max_cy = clamp(int((b.ymax - p.min_y) / lp.cell_h), 0, int(lp.grid_dim - 1));
}

inline uint select_level_for_box(BoundingBox b, constant HierarchicalGridParams& p) {
    // Select the finest level where box covers at most 4 cells (from level num_levels-1 down to 0)
    for (int lvl = int(p.num_levels - 1); lvl > 0; --lvl) {
        int min_cx, max_cx, min_cy, max_cy;
        get_level_cell_range(b, p, lvl, min_cx, max_cx, min_cy, max_cy);
        int count = (max_cx - min_cx + 1) * (max_cy - min_cy + 1);
        if (count <= 4) {
            return lvl;
        }
    }
    return 0; // Coarsest level covers at most 4 cells
}

// Pass 1: Count entries per cell across all levels
kernel void count_cell_entries(
    device const BoundingBox*             boxes       [[buffer(0)]],
    device atomic_uint*                   cell_counts [[buffer(1)]],
    constant HierarchicalGridParams&      p           [[buffer(2)]],
    uint                                  tid         [[thread_position_in_grid]])
{
    if (tid >= p.num_build) return;
    BoundingBox b = boxes[tid];
    if (!is_valid_box(b)) return;

    uint lvl = select_level_for_box(b, p);
    constant GridLevelParams& lp = p.levels[lvl];

    int min_cx, max_cx, min_cy, max_cy;
    get_level_cell_range(b, p, lvl, min_cx, max_cx, min_cy, max_cy);

    for (int y = min_cy; y <= max_cy; ++y) {
        for (int x = min_cx; x <= max_cx; ++x) {
            uint cell_idx = lp.cell_offset + y * lp.grid_dim + x;
            atomic_fetch_add_explicit(&cell_counts[cell_idx], 1, memory_order_relaxed);
        }
    }
}

// Pass 2: Populate cell entries into hierarchical grid
kernel void populate_cells(
    device const BoundingBox*             boxes        [[buffer(0)]],
    device atomic_uint*                   cell_heads   [[buffer(1)]],
    device const uint*                    cell_offsets [[buffer(2)]],
    device uint*                          cell_entries [[buffer(3)]],
    constant HierarchicalGridParams&      p            [[buffer(4)]],
    uint                                  tid          [[thread_position_in_grid]])
{
    if (tid >= p.num_build) return;
    BoundingBox b = boxes[tid];
    if (!is_valid_box(b)) return;

    uint lvl = select_level_for_box(b, p);
    constant GridLevelParams& lp = p.levels[lvl];

    int min_cx, max_cx, min_cy, max_cy;
    get_level_cell_range(b, p, lvl, min_cx, max_cx, min_cy, max_cy);

    for (int y = min_cy; y <= max_cy; ++y) {
        for (int x = min_cx; x <= max_cx; ++x) {
            uint cell_idx = lp.cell_offset + y * lp.grid_dim + x;
            uint slot = atomic_fetch_add_explicit(&cell_heads[cell_idx], 1, memory_order_relaxed);
            cell_entries[cell_offsets[cell_idx] + slot] = tid;
        }
    }
}

// Pass 3: Probe hierarchical grid visiting every level
kernel void probe_grid(
    device const BoundingBox*             build_boxes  [[buffer(0)]],
    device const BoundingBox*             probe_boxes  [[buffer(1)]],
    device const uint*                    cell_offsets [[buffer(2)]],
    device const uint*                    cell_entries [[buffer(3)]],
    device MatchPair*                     output_pairs [[buffer(4)]],
    device atomic_uint*                   match_count  [[buffer(5)]],
    constant HierarchicalGridParams&      p            [[buffer(6)]],
    uint                                  tid          [[thread_position_in_grid]])
{
    if (tid >= p.num_probe || p.num_build == 0) return;
    uint probe_idx = p.probe_offset + tid;
    BoundingBox probe = probe_boxes[probe_idx];
    if (!is_valid_box(probe)) return;

    // A probe visits every level of the hierarchy
    for (uint lvl = 0; lvl < p.num_levels; ++lvl) {
        constant GridLevelParams& lp = p.levels[lvl];
        float max_grid_x = p.min_x + lp.cell_w * float(lp.grid_dim);
        float max_grid_y = p.min_y + lp.cell_h * float(lp.grid_dim);
        if (probe.xmax < p.min_x || probe.xmin > max_grid_x ||
            probe.ymax < p.min_y || probe.ymin > max_grid_y) {
            continue;
        }

        int p_min_cx, p_max_cx, p_min_cy, p_max_cy;
        get_level_cell_range(probe, p, lvl, p_min_cx, p_max_cx, p_min_cy, p_max_cy);

        for (int cy = p_min_cy; cy <= p_max_cy; ++cy) {
            for (int cx = p_min_cx; cx <= p_max_cx; ++cx) {
                uint cell_idx = lp.cell_offset + cy * lp.grid_dim + cx;
                uint start = cell_offsets[cell_idx];
                uint end = cell_offsets[cell_idx + 1];

                for (uint i = start; i < end; ++i) {
                    uint build_id = cell_entries[i];
                    BoundingBox build = build_boxes[build_id];
                    if (boxes_intersect(build, probe)) {
                        int b_min_cx, b_max_cx, b_min_cy, b_max_cy;
                        get_level_cell_range(build, p, lvl, b_min_cx, b_max_cx, b_min_cy, b_max_cy);
                        // Deduplication rule per level: emit only in the minimum common cell
                        if (cx == max(p_min_cx, b_min_cx) && cy == max(p_min_cy, b_min_cy)) {
                            uint slot = atomic_fetch_add_explicit(match_count, 1, memory_order_relaxed);
                            if (slot < p.max_results) {
                                output_pairs[slot] = MatchPair{build_id, probe_idx};
                            }
                        }
                    }
                }
            }
        }
    }
}

)RAW_SHADER";

static const char* REFINE_METAL_SOURCE = R"RAW_SHADER(
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#include <metal_stdlib>
#include "geom_types.hpp"
using namespace metal;

// 2D Line segment orientation:
// Returns:
//   1: q is strictly to the right of p1->p2
//  -1: q is strictly to the left of p1->p2
//   0: q is collinear with p1->p2
inline int get_orientation(Point2D p1, Point2D p2, Point2D q) {
    float d_x = q.x - p1.x;
    float d_y = q.y - p1.y;
    if (metal::abs(d_x) <= 1e-7f && metal::abs(d_y) <= 1e-7f) {
        return 0;
    }
    float v1 = d_x * (p2.y - p1.y);
    float v2 = (p2.x - p1.x) * d_y;
    if (metal::abs(v1 - v2) <= 1e-7f) {
        return 0;
    }
    return (v1 - v2 < 0.0f) ? -1 : 1;
}

// Check whether collinear point q lies within bounding box of segment (p1, p2)
inline bool segment_covers(Point2D p1, Point2D p2, Point2D q) {
    float min_x = metal::min(p1.x, p2.x) - 1e-6f;
    float max_x = metal::max(p1.x, p2.x) + 1e-6f;
    float min_y = metal::min(p1.y, p2.y) - 1e-6f;
    float max_y = metal::max(p1.y, p2.y) + 1e-6f;
    return (q.x >= min_x && q.x <= max_x && q.y >= min_y && q.y <= max_y);
}

// Locate point in a single linear ring using winding number algorithm
inline PointLocation locate_point_in_ring(
    Point2D p,
    device const Point2D* vertices,
    uint32_t start_idx,
    uint32_t num_points)
{
    if (num_points < 3) return kPointOutside;

    Point2D first_pt = vertices[start_idx];
    Point2D last_pt = vertices[start_idx + num_points - 1];
    bool is_closed = (first_pt.x == last_pt.x && first_pt.y == last_pt.y);
    uint32_t num_segments = is_closed ? (num_points - 1) : num_points;

    int wn = 0;

    for (uint32_t i = 0; i < num_segments; ++i) {
        Point2D p1 = vertices[start_idx + i];
        Point2D p2 = vertices[start_idx + ((i + 1) % num_points)];

        // Zero-length segments are ignored
        if (p1.x == p2.x && p1.y == p2.y) continue;

        int side = get_orientation(p1, p2, p);
        if (side == 0) {
            if (segment_covers(p1, p2, p)) {
                return kPointBoundary;
            }
        }

        bool is_rising = (p1.y <= p.y) && (p.y < p2.y) && (side == 1);
        bool is_falling = (p2.y <= p.y) && (p.y < p1.y) && (side == -1);
        wn += (is_rising ? 1 : 0) - (is_falling ? 1 : 0);
    }

    if (wn == 0) return kPointOutside;
    return kPointInside;
}

// Exact point location in a polygon (outer ring + interior hole rings)
inline PointLocation locate_point_in_polygon(
    Point2D p,
    PolygonGeom poly,
    device const PolygonRing* rings,
    device const Point2D* vertices)
{
    // 1. Check outer ring
    PolygonRing outer = rings[poly.outer_ring_idx];
    PointLocation outer_loc = locate_point_in_ring(p, vertices, outer.start_idx, outer.num_points);

    if (outer_loc == kPointOutside) {
        return kPointOutside;
    }

    PointLocation rloc = outer_loc;

    // 2. Check interior rings (holes)
    for (uint32_t h = 0; h < poly.num_interior_rings; ++h) {
        PolygonRing hole = rings[poly.outer_ring_idx + 1 + h];
        PointLocation hole_loc = locate_point_in_ring(p, vertices, hole.start_idx, hole.num_points);

        if (hole_loc == kPointInside) {
            // Inside a hole -> outside the polygon
            return kPointOutside;
        }
        if (hole_loc == kPointBoundary) {
            rloc = kPointBoundary;
        }
    }

    return rloc;
}

// Stage 2 Geometric Refinement Kernel:
// Dispatched with 1 thread per CandidatePair.
// Points located inside outer ring and outside all holes are retained.
kernel void point_in_polygon_refine(
    device const CandidatePair* candidate_pairs  [[buffer(0)]],
    device const PolygonGeom*   polygons         [[buffer(1)]],
    device const PolygonRing*   rings            [[buffer(2)]],
    device const Point2D*       vertices         [[buffer(3)]],
    device const Point2D*       points           [[buffer(4)]],
    device CandidatePair*       output_refined   [[buffer(5)]],
    device atomic_uint*         refined_count    [[buffer(6)]],
    constant uint&              num_candidates   [[buffer(7)]],
    constant uint&              max_results      [[buffer(8)]],
    uint                        thread_id        [[thread_position_in_grid]])
{
    if (thread_id >= num_candidates) return;

    CandidatePair pair = candidate_pairs[thread_id];
    PolygonGeom poly = polygons[pair.polygon_idx];
    Point2D pt = points[pair.point_idx];

    PointLocation loc = locate_point_in_polygon(pt, poly, rings, vertices);

    if (loc != kPointOutside) {
        uint slot = atomic_fetch_add_explicit(refined_count, 1, memory_order_relaxed);
        if (slot < max_results) {
            output_refined[slot] = pair;
        }
    }
}

)RAW_SHADER";
